export default [{
  title: 'Thank you!',
  content: '',
  icon: 'ios-star',
  headerColor: '#ffffff',
  headerIconColor: '#ef2d32',
  headerBkgColor: '#ef2d32',
}, {
  title: 'Well done!',
  content: '',
  icon: 'ios-medal',
  headerColor: '#ffffff',
  headerIconColor: '#66d44b',
  headerBkgColor: '#66d44b',
}, {
  title: 'Great job!',
  content: '',
  icon: 'ios-thumbs-up',
  headerColor: '#ffffff',
  headerIconColor: '#2d95ef',
  headerBkgColor: '#2d95ef',
}, {
  title: 'Awesome!',
  content: '',
  icon: 'ios-rocket',
  headerColor: '#ffffff',
  headerIconColor: '#5755b7',
  headerBkgColor: '#5755b7',
}, {
  title: 'Congratulations!',
  content: '',
  icon: 'ios-trophy',
  headerColor: '#ffffff',
  headerIconColor: '#ff8300',
  headerBkgColor: '#ff8300',
}, {
  title: 'Very happy!',
  content: '',
  icon: 'ios-happy',
  headerColor: '#ffffff',
  headerIconColor: '#2dcbef',
  headerBkgColor: '#2dcbef',
}, {
  title: 'Many thanks!',
  content: '',
  icon: 'ios-heart',
  headerColor: '#ffffff',
  headerIconColor: '#ef2d6c',
  headerBkgColor: '#ef2d6c',
}, {
  title: 'You\'re so helpful!',
  content: '',
  icon: 'ios-beer',
  headerColor: '#ffffff',
  headerIconColor: '#ffd400',
  headerBkgColor: '#ffd400',
}, {
  title: 'Much obliged!',
  content: '',
  icon: 'ios-gift',
  headerColor: '#ffffff',
  headerIconColor: '#40b987',
  headerBkgColor: '#40b987',
}];
